# Generated by Django 2.1 on 2018-08-09 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180809_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to=settings.AUTH_USER_MODEL),
        ),
    ]
