# Generated by Django 2.1 on 2018-08-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180809_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='owner',
        ),
    ]
