# Generated by Django 2.1 on 2018-08-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180809_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='owner',
        ),
    ]
