# Generated by Django 2.1 on 2018-08-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_issue_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='date_modified',
        ),
    ]
